name: WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch: # allows manual runs

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
